### ISSUE TITLE
Report doesn't works

### ISSUE THREAD

**Issue by callimac-o** [JKBert/knoda5#1]
Hi, I have installed hk_classes and knoda5 on Debian9 and they work fine. I only have a problem with the reports: the drawing panel works but when press button view appear the pdf code and not the report view.

I have encountered some problems installing both knoda and hk_klasses: if it is useful I can write them as I managed to solve them.

Thanks

**Comment by JKBert** [comment]
Hi.
Which kind of trouble ? hkc configure process can hang after "checking for a version of Python >= '2.1.0'... yes". To build this library, I manually patch configure script. I will try to fix this issue as soon as possible but this issue seems to be in autoconf package. But if I remember, configure script should run out of the box on a recent Debian distribution.

There are also some issues later with python I will try to fix.

Unfortunately, I have to fix hkclasses before trying to investigate your specific bug. But, please, can you post here some screenshots ? I'm not very familiar with knoda, I've only patched this dying software as my wife has to reopen some very old databases that have been created with knoda3...
JKB

**Comment by callimac-o** [comment]
Ciao  JKB,

Thank you for your answer. I enclose two screenshots related to the problem with reports.
I'm sorry this application is dying I have been using it for my accounting since 2004 and I find it very well done. I always search on the net but I can't find a similar one unless I go back to using Microsoft access.
Other issues I have talked about are installation related and if it would be helpful for someone like me who is impractical with compiling, I can submit them.
If I can be useful in some way for the project, gladly, even if unfortunately I am not very familiar with programming, I only know python and sql that I use with knoda; I also did the Italian translation of the messages.
Ciao e grazie Callimaco 

![Screenshot_20211115_122916](https://user-images.githubusercontent.com/94168790/141825976-d6f96406-5327-489d-853d-c1a276b0bfb5.png)
![Screenshot_20211115_122959](https://user-images.githubusercontent.com/94168790/141825978-34e5a564-155b-4730-8077-c7f0b9a44acb.png)

On the first screenshot, the design panel that works fine, on the second what appear after puhs the button view

**Comment by callimac-o** [comment]
this message was sent me by Patrick Hanak, developer of knoda on sourceforge

Hi Livio !

I guess the issue is related to knoda5 and its usage on debian9 distribution.
I have got some experience with the issue you described. The report generated by knodaX + hk_classes is actually PostScript ( *.ps) file. To preview it on the screen,
a viewer is needed. KnodaX relies on KDE system to provide a proper viewer. In various distributions, okular application is the right viewer for ps files. Unfortunately, there is
configuration debian9 + knoda5 + okular which does not work, okular is not registered as ps viewer in KDE Frameworks 5 environment, I do not know why. I use configuration
opensuse + knoda5 + okular and it works well. 
At the moment, if you do not want to change Linux distribution, I can recommend  the only one solution: use knoda4 instead of knoda5.

Br

Patrik Hanak

**Comment by callimac-o** [comment]
Ciao,
I upgraded my Debian distribution from 9 to 11. Now the report preview works. For actual printing, the printer name must be entered in the print command setting.
Hi thanks for your work. 
Callimaco
